# org: freddieentity
# app: serverless-todo-app
service: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  environment:
    AUTH_0_JWKS_URL: https://dev-tp1uyfva.au.auth0.com/.well-known/jwks.json

  iamRoleStatements:
    - ${file(iam/ObservabilityIAM.yml):XRayCommon}


functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

resources:
  Resources:
    GatewayResponseDefault4XX: ${file(resources/GatewayResponseDefault.yml):GatewayResponseDefault4XX}