TodosTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
        - AttributeName: todoId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
    KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: todoId
          KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    LocalSecondaryIndexes:
      - IndexName: ${self:provider.environment.TODOS_CREATED_AT_INDEX}
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    TableName: ${self:provider.environment.TODOS_TABLE}